struct CPUState;

void qemu_flog(const char*);
unsigned long qemu_page_size();
unsigned long qemu_mmap_stack(unsigned long len);
unsigned long qemu_mmap(unsigned long len);
unsigned long qemu_offset();
void qemu_disas(unsigned long pos);
void qemu_setup_segments(CPUState *envp);
void qemu_set_eip(CPUState *envp, unsigned long eip);
void qemu_set_esp(CPUState *envp, unsigned long esp);
int qemu_set_jmp(CPUState *envp);
void qemu_reset(CPUState *envp);
CPUState* qemu_cpu_init();
int qemu_exception_index(CPUState *envp);
unsigned long qemu_pos(CPUState *envp);
void qemu_init();
int qemu_exec_start(CPUState *env1);
void qemu_exec_end(CPUState *env1);
void qemu_exec_middle(CPUState *env1);